### ISSUE TITLE
Rename "For You" to "Following"

### ISSUE THREAD

**Issue by nunomaduro** [pinkary-project/pinkary.com#453]

**Comment by darren-glanville** [comment]
I'm happy to work on this if that helps

**Comment by Moemen-Gaballah** [comment]
Good Morning Guys.

I have created a [PR](https://github.com/pinkary-project/pinkary.com/pull/587) for this "rename for you to following" #587 
 @msamgan @nunomaduro 

Do you have any comments or suggestions?

Thanks

**Comment by msamgan** [comment]
@MrPunyapal @nunomaduro can you please close this issue.
