### ISSUE TITLE
Share button in question/show page 

### ISSUE THREAD

**Issue by MrPunyapal** [pinkary-project/pinkary.com#502]
In the show page if the user clicks on the share button it does some UI flickers with the header 👇 

https://github.com/user-attachments/assets/aba565f4-f25a-41da-b255-6163b879b67b

**Comment by fcarboneras** [comment]
@MrPunyapal i did look at it on the browser and on my iphone, and i did not have this issue. Do you still have it on your android phone ? it looks like the hamburger menu goes out the window when you click on share, but i can not reproduce this behaviour.
