### ISSUE TITLE
Fix: handle image validation where the post is close to 1000 chars

### ISSUE THREAD

**Issue by CamKem** [pinkary-project/pinkary.com#508]
As pointed out by @MrPunyapal - if someone is making a long post, and it's close to the character limit, then they try and and an image it will fail, but not gracefully - we need to handle this with validator or some other mechanism / logic.

**Comment by ozdemirrulass** [comment]
Is the expected behavior that the question should be 1000 characters long plus an uploaded image snippet, or should the combined total of the question and uploaded image snippet be 1000 characters?

**Comment by CamKem** [comment]
@ozdemirrulass it should be 1000 characters max. So if the image is going to take the post over 1000 characters when the markdown is parsed & about to be added. We should display an error message, not insert the markdown & the image will still be displayed in the preview under the text box. This allows a user to click & insert the markdown again. So they can shorten their text & insert it again.

This validation should run on the client-side when someone tries to click the image preview to insert the markdown. If it takes the post over 1000 chars, it gives a validation error.
