### ISSUE TITLE
Don't send email if there are no notifications unread

### ISSUE THREAD

**Issue by danielpetrica** [pinkary-project/pinkary.com#590]
I received an email stating that I have 0 notifications to read. while it's not too annoying it is a bit confusing. can we disable it 
Here's the mail:
![Arc 2024-09-09 17 05 36](https://github.com/user-attachments/assets/5059460a-7db3-466c-9e44-9bb4ab49794b)
Here's my username if needed for debug: pinkary.com/@danielpetrica

**Comment by danielpetrica** [comment]
Can I submit a pr for this?

**Comment by MrPunyapal** [comment]
> Can I submit a pr for this?

Why not!

**Comment by danielpetrica** [comment]
@MrPunyapal
I saw a commit about emails from you, i was worried it may conflict with it. I'll try opening a pr request now
