### ISSUE TITLE
Migration issue when tried to change DB from Sqlite to MySql. 

### ISSUE THREAD

**Issue by amitm13** [pinkary-project/pinkary.com#612]
I attempted to switch the database from SQLite to MySQL, but encountered an error. Additionally, there is an issue with the foreign key in the "likes" table, specifically regarding the reference to the question ID.

**Comment by yogesh16** [comment]
This [PR #628](https://github.com/pinkary-project/pinkary.com/pull/628) fix the issue.

**Comment by MrPunyapal** [comment]
No plans
