### ISSUE TITLE
PerformDatabaseBackupCommandTest failing

### ISSUE THREAD

**Issue by harris21** [pinkary-project/pinkary.com#613]
I just cloned and tried to run `composer test` full suite and got the following error:

<img width="1488" alt="Screenshot 2024-09-15 at 19 24 41" src="https://github.com/user-attachments/assets/c0b220b7-33f9-494f-8f40-7086494452d7">

remember a discussion in the Telegram group fairly recently, where @nunomaduro mentioned that we now keep the 4 latest backups only, so this might be related to that.

I went a little deeper and realised that there might be an issue with the backup deletion implementation. 
Inside `PerformDatabaseBackupCommand`, there is the following part:
```php
collect($glob)->sort()->reverse()->slice(4)->each(
    fn (string $backup): bool => File::delete($backup),
);
```

I believe that `sort()` in this case (at least on this test, but this might also propagate in the production backups) doesn't sort correctly based on the name. In the following output, backup-18 up to backup-21 should have been sliced out, but the `sort()` method sorts the numbers 1, 10, 11 etc. first (see image below, for output `collect($glob)->sort()` )

<img width="873" alt="Screenshot 2024-09-15 at 19 34 42" src="https://github.com/user-attachments/assets/82a20d88-0e9f-4dff-8f81-3ac0b4197a74">

All in all, the final result is the following (for output `collect($glob)->sort()->reverse()->slice(4)`)

<img width="893" alt="Screenshot 2024-09-15 at 19 25 14" src="https://github.com/user-attachments/assets/d467746a-8f2f-4057-a3fa-8e888135e1a2">

**Comment by addeeandra** [comment]
I was not following the backup discussion, but I tried the PR from @MrPunyapal here #608 and it succeed. So, it seems we don't need to test 21 backup files.

**Comment by harris21** [comment]
Nice! So once #608 is merged, the issue should be fixed.
