### ISSUE TITLE
Feat: Search anything

### ISSUE THREAD

**Issue by aagjalpankaj** [pinkary-project/pinkary.com#710]
Currently we can only search users. Would be nice if we can search anything including posts.

e.g.
<img width="568" alt="image" src="https://github.com/user-attachments/assets/59245280-14f6-460c-9f7b-08e9a7e9eb61">

**Comment by vamsiKrishna0315** [comment]
yeah like X bringing  the posts with the keyword we have searched

**Comment by CamKem** [comment]
This is being handled in #375 and will be included in the new design UI in #733
